// Code generated by protoc-gen-go. DO NOT EDIT.
// source: makepdf.proto

package makepdf

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PDFParams struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Delay                int32    `protobuf:"varint,2,opt,name=delay,proto3" json:"delay,omitempty"`
	JavascriptReadyFlag  string   `protobuf:"bytes,3,opt,name=javascriptReadyFlag,proto3" json:"javascriptReadyFlag,omitempty"`
	IsDebug              bool     `protobuf:"varint,4,opt,name=isDebug,proto3" json:"isDebug,omitempty"`
	IsMarginless         bool     `protobuf:"varint,5,opt,name=isMarginless,proto3" json:"isMarginless,omitempty"`
	IsLandscape          bool     `protobuf:"varint,6,opt,name=isLandscape,proto3" json:"isLandscape,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PDFParams) Reset()         { *m = PDFParams{} }
func (m *PDFParams) String() string { return proto.CompactTextString(m) }
func (*PDFParams) ProtoMessage()    {}
func (*PDFParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ba64ad676e34f5a, []int{0}
}

func (m *PDFParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PDFParams.Unmarshal(m, b)
}
func (m *PDFParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PDFParams.Marshal(b, m, deterministic)
}
func (m *PDFParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PDFParams.Merge(m, src)
}
func (m *PDFParams) XXX_Size() int {
	return xxx_messageInfo_PDFParams.Size(m)
}
func (m *PDFParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PDFParams.DiscardUnknown(m)
}

var xxx_messageInfo_PDFParams proto.InternalMessageInfo

func (m *PDFParams) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PDFParams) GetDelay() int32 {
	if m != nil {
		return m.Delay
	}
	return 0
}

func (m *PDFParams) GetJavascriptReadyFlag() string {
	if m != nil {
		return m.JavascriptReadyFlag
	}
	return ""
}

func (m *PDFParams) GetIsDebug() bool {
	if m != nil {
		return m.IsDebug
	}
	return false
}

func (m *PDFParams) GetIsMarginless() bool {
	if m != nil {
		return m.IsMarginless
	}
	return false
}

func (m *PDFParams) GetIsLandscape() bool {
	if m != nil {
		return m.IsLandscape
	}
	return false
}

type PDFFile struct {
	Binary               []byte   `protobuf:"bytes,1,opt,name=binary,proto3" json:"binary,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PDFFile) Reset()         { *m = PDFFile{} }
func (m *PDFFile) String() string { return proto.CompactTextString(m) }
func (*PDFFile) ProtoMessage()    {}
func (*PDFFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_4ba64ad676e34f5a, []int{1}
}

func (m *PDFFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PDFFile.Unmarshal(m, b)
}
func (m *PDFFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PDFFile.Marshal(b, m, deterministic)
}
func (m *PDFFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PDFFile.Merge(m, src)
}
func (m *PDFFile) XXX_Size() int {
	return xxx_messageInfo_PDFFile.Size(m)
}
func (m *PDFFile) XXX_DiscardUnknown() {
	xxx_messageInfo_PDFFile.DiscardUnknown(m)
}

var xxx_messageInfo_PDFFile proto.InternalMessageInfo

func (m *PDFFile) GetBinary() []byte {
	if m != nil {
		return m.Binary
	}
	return nil
}

func (m *PDFFile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*PDFParams)(nil), "makepdf.PDFParams")
	proto.RegisterType((*PDFFile)(nil), "makepdf.PDFFile")
}

func init() {
	proto.RegisterFile("makepdf.proto", fileDescriptor_4ba64ad676e34f5a)
}

var fileDescriptor_4ba64ad676e34f5a = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xdf, 0x4a, 0xf3, 0x40,
	0x10, 0xc5, 0xbf, 0x7c, 0xfd, 0x13, 0x3b, 0xb6, 0x50, 0x46, 0x91, 0x45, 0x10, 0x42, 0xae, 0x7a,
	0x15, 0x45, 0x11, 0xef, 0x4b, 0x88, 0x37, 0x2d, 0x2c, 0x0b, 0x3e, 0xc0, 0xb4, 0x19, 0xcb, 0xb6,
	0xc9, 0x26, 0xec, 0xb6, 0x85, 0xf8, 0x7e, 0xbe, 0x97, 0x64, 0x4d, 0xa5, 0x82, 0x77, 0xf3, 0x3b,
	0x73, 0x76, 0x87, 0x39, 0x03, 0x93, 0x92, 0x76, 0x5c, 0xe7, 0xef, 0x49, 0x6d, 0xab, 0x7d, 0x85,
	0x61, 0x87, 0xf1, 0x67, 0x00, 0x23, 0x99, 0x66, 0x92, 0x2c, 0x95, 0x0e, 0xa7, 0xd0, 0x3b, 0xd8,
	0x42, 0x04, 0x51, 0x30, 0x1b, 0xa9, 0xb6, 0xc4, 0x6b, 0x18, 0xe4, 0x5c, 0x50, 0x23, 0xfe, 0x47,
	0xc1, 0x6c, 0xa0, 0xbe, 0x01, 0x1f, 0xe0, 0x6a, 0x4b, 0x47, 0x72, 0x6b, 0xab, 0xeb, 0xbd, 0x62,
	0xca, 0x9b, 0xac, 0xa0, 0x8d, 0xe8, 0xf9, 0x77, 0x7f, 0xb5, 0x50, 0x40, 0xa8, 0x5d, 0xca, 0xab,
	0xc3, 0x46, 0xf4, 0xa3, 0x60, 0x76, 0xa1, 0x4e, 0x88, 0x31, 0x8c, 0xb5, 0x5b, 0x92, 0xdd, 0x68,
	0x53, 0xb0, 0x73, 0x62, 0xe0, 0xdb, 0xbf, 0x34, 0x8c, 0xe0, 0x52, 0xbb, 0x05, 0x99, 0xdc, 0xad,
	0xa9, 0x66, 0x31, 0xf4, 0x96, 0x73, 0x29, 0x7e, 0x86, 0x50, 0xa6, 0x59, 0xa6, 0x0b, 0xc6, 0x1b,
	0x18, 0xae, 0xb4, 0x21, 0xdb, 0xf8, 0x3d, 0xc6, 0xaa, 0x23, 0x44, 0xe8, 0x1b, 0x2a, 0xd9, 0x6f,
	0x32, 0x52, 0xbe, 0x7e, 0x9c, 0x43, 0xb8, 0xa4, 0x1d, 0xcb, 0x34, 0xc3, 0x17, 0x98, 0xbc, 0xf2,
	0xbe, 0xfd, 0xc4, 0x56, 0xe5, 0x9b, 0x5a, 0x20, 0x26, 0xa7, 0xcc, 0x7e, 0x02, 0xba, 0x9d, 0x9e,
	0x6b, 0xed, 0xb4, 0xf8, 0xdf, 0xfc, 0x1e, 0xee, 0xcc, 0x47, 0xb2, 0xae, 0x12, 0xc3, 0x36, 0x6f,
	0x92, 0x2d, 0xf3, 0x91, 0x5d, 0x6b, 0xe9, 0xac, 0xf3, 0x71, 0x37, 0x42, 0xb6, 0xd1, 0xcb, 0x60,
	0x35, 0xf4, 0x37, 0x78, 0xfa, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x06, 0x94, 0x09, 0xad, 0x94, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MakePDFClient is the client API for MakePDF service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MakePDFClient interface {
	GetPDFFromURL(ctx context.Context, in *PDFParams, opts ...grpc.CallOption) (*PDFFile, error)
}

type makePDFClient struct {
	cc grpc.ClientConnInterface
}

func NewMakePDFClient(cc grpc.ClientConnInterface) MakePDFClient {
	return &makePDFClient{cc}
}

func (c *makePDFClient) GetPDFFromURL(ctx context.Context, in *PDFParams, opts ...grpc.CallOption) (*PDFFile, error) {
	out := new(PDFFile)
	err := c.cc.Invoke(ctx, "/makepdf.MakePDF/GetPDFFromURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MakePDFServer is the server API for MakePDF service.
type MakePDFServer interface {
	GetPDFFromURL(context.Context, *PDFParams) (*PDFFile, error)
}

// UnimplementedMakePDFServer can be embedded to have forward compatible implementations.
type UnimplementedMakePDFServer struct {
}

func (*UnimplementedMakePDFServer) GetPDFFromURL(ctx context.Context, req *PDFParams) (*PDFFile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPDFFromURL not implemented")
}

func RegisterMakePDFServer(s *grpc.Server, srv MakePDFServer) {
	s.RegisterService(&_MakePDF_serviceDesc, srv)
}

func _MakePDF_GetPDFFromURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PDFParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MakePDFServer).GetPDFFromURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/makepdf.MakePDF/GetPDFFromURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MakePDFServer).GetPDFFromURL(ctx, req.(*PDFParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _MakePDF_serviceDesc = grpc.ServiceDesc{
	ServiceName: "makepdf.MakePDF",
	HandlerType: (*MakePDFServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPDFFromURL",
			Handler:    _MakePDF_GetPDFFromURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "makepdf.proto",
}
